fix: check if you already are on newbranch

diff --git a/commit b/commit
--- a/commit
+++ b/commit
@@ -3,7 +3,6 @@
 
 trimSpace() {
         echo $1 | tr -d [:space:] | sed "s/:/\//"
-        # gerer les different cas ou le nom de branch serait incorrect
 }
 
 if [[ ! $2 ]]
@@ -13,23 +12,24 @@ if [[ ! $2 ]]
 		message=$1
         elif [[ ! $3 ]]
 	then                 
-                newbranch=$(trimSpace "$2")
-                [[ $? = 1 ]] && { echo "invalid newbranch or message"; exit 1; }
+		newbranch=$(trimSpace "$2")
+		[[ $? = 1 ]] && { echo "invalid newbranch or message"; exit 1; }
 		message=$2
 		origin=$1
 	else 
  		newbranch=$(trimSpace "$2")
-                [[ $? = 1 ]] && { echo "invalid newbranch or message"; exit 1; }
-                message=$3
+		[[ $? = 1 ]] && { echo "invalid newbranch or message"; exit 1; }
+		message=$3
 		origin=$1
 fi
 
 executeGitCommands() {
         remote=$(git remote)
+		currentbranch=$(git status -s -b | tr -d "## ")
         (
-		set -e
-		[[ $2 ]] && git checkout $origin
-        	git branch $newbranch
+			set -e
+			[[ $2 ]] && git checkout $origin
+        	[[ $currentbranch != $newbranch ]] && git branch $newbranch
         	git checkout $newbranch
         	git commit -m "$message"
         	git push -u $remote $newbranch 
